import { GalleryMediaItem, GalleryItem, GalleryCategory } from '../types';

/**
 * BEAJAY COUTURE BRIDAL — OFFICIAL GALLERY MEDIA REGISTRY
 *
 * Grounded strictly in physically verified files present in /public/media/gallery/
 * Total physical files: 65 official photographs (numbered 1.jpg to 65.jpg).
 *
 * Media System Separation Guarantee:
 * - Independent from BJ gown catalog records
 * - Independent from the 51 official Collection assets in /public/media/collections/
 * - Independent from rental inventory
 */

export const GALLERY_FILTERS: { id: GalleryCategory; label: string }[] = [
  { id: 'all', label: 'ALL MOMENTS' },
  { id: 'bridal-portraits', label: 'BRIDAL PORTRAITS' },
  { id: 'couture-details', label: 'COUTURE DETAILS' },
  { id: 'fittings-bts', label: 'FITTINGS & BEHIND THE SCENES' },
];

/**
 * Complete inventory of 65 physically verified official Gallery media items
 */
export const OFFICIAL_GALLERY_ITEMS: GalleryMediaItem[] = [
  {
    id: 'gallery-01',
    src: '/media/gallery/1.jpg',
    image: '/media/gallery/1.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-02',
    src: '/media/gallery/2.jpg',
    image: '/media/gallery/2.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-03',
    src: '/media/gallery/3.jpg',
    image: '/media/gallery/3.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-04',
    src: '/media/gallery/4.jpg',
    image: '/media/gallery/4.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-05',
    src: '/media/gallery/5.jpg',
    image: '/media/gallery/5.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-06',
    src: '/media/gallery/6.jpg',
    image: '/media/gallery/6.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-07',
    src: '/media/gallery/7.jpg',
    image: '/media/gallery/7.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-08',
    src: '/media/gallery/8.jpeg',
    image: '/media/gallery/8.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[16/9]',
    orientation: 'landscape',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-09',
    src: '/media/gallery/9.jpg',
    image: '/media/gallery/9.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-10',
    src: '/media/gallery/10.jpg',
    image: '/media/gallery/10.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-11',
    src: '/media/gallery/11.jpg',
    image: '/media/gallery/11.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-12',
    src: '/media/gallery/12.jpg',
    image: '/media/gallery/12.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-13',
    src: '/media/gallery/13.jpg',
    image: '/media/gallery/13.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-14',
    src: '/media/gallery/14.jpg',
    image: '/media/gallery/14.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-15',
    src: '/media/gallery/15.jpg',
    image: '/media/gallery/15.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-16',
    src: '/media/gallery/16.jpg',
    image: '/media/gallery/16.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-17',
    src: '/media/gallery/17.jpg',
    image: '/media/gallery/17.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-18',
    src: '/media/gallery/18.jpg',
    image: '/media/gallery/18.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-19',
    src: '/media/gallery/19.jpg',
    image: '/media/gallery/19.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-20',
    src: '/media/gallery/20.jpg',
    image: '/media/gallery/20.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-21',
    src: '/media/gallery/21.jpg',
    image: '/media/gallery/21.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-22',
    src: '/media/gallery/22.jpeg',
    image: '/media/gallery/22.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-23',
    src: '/media/gallery/23.jpg',
    image: '/media/gallery/23.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-24',
    src: '/media/gallery/24.jpg',
    image: '/media/gallery/24.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-25',
    src: '/media/gallery/25.jpg',
    image: '/media/gallery/25.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-26',
    src: '/media/gallery/26.jpg',
    image: '/media/gallery/26.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-27',
    src: '/media/gallery/27.jpg',
    image: '/media/gallery/27.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-28',
    src: '/media/gallery/28.jpg',
    image: '/media/gallery/28.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-29',
    src: '/media/gallery/29.jpg',
    image: '/media/gallery/29.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-30',
    src: '/media/gallery/30.jpg',
    image: '/media/gallery/30.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-31',
    src: '/media/gallery/31.jpg',
    image: '/media/gallery/31.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-32',
    src: '/media/gallery/32.jpg',
    image: '/media/gallery/32.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-33',
    src: '/media/gallery/33.jpg',
    image: '/media/gallery/33.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-34',
    src: '/media/gallery/34.jpg',
    image: '/media/gallery/34.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-35',
    src: '/media/gallery/35.jpg',
    image: '/media/gallery/35.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-36',
    src: '/media/gallery/36.jpg',
    image: '/media/gallery/36.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-37',
    src: '/media/gallery/37.jpg',
    image: '/media/gallery/37.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-38',
    src: '/media/gallery/38.jpg',
    image: '/media/gallery/38.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-39',
    src: '/media/gallery/39.jpg',
    image: '/media/gallery/39.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-40',
    src: '/media/gallery/40.jpg',
    image: '/media/gallery/40.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-41',
    src: '/media/gallery/41.jpg',
    image: '/media/gallery/41.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-42',
    src: '/media/gallery/42.jpg',
    image: '/media/gallery/42.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-43',
    src: '/media/gallery/43.jpeg',
    image: '/media/gallery/43.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-44',
    src: '/media/gallery/44.jpeg',
    image: '/media/gallery/44.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-45',
    src: '/media/gallery/45.jpeg',
    image: '/media/gallery/45.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-46',
    src: '/media/gallery/46.jpeg',
    image: '/media/gallery/46.jpeg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-47',
    src: '/media/gallery/47.jpg',
    image: '/media/gallery/47.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-48',
    src: '/media/gallery/48.jpg',
    image: '/media/gallery/48.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-49',
    src: '/media/gallery/49.jpg',
    image: '/media/gallery/49.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-50',
    src: '/media/gallery/50.webp',
    image: '/media/gallery/50.webp',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-51',
    src: '/media/gallery/51.jpg',
    image: '/media/gallery/51.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-52',
    src: '/media/gallery/52.jpg',
    image: '/media/gallery/52.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-53',
    src: '/media/gallery/53.jpg',
    image: '/media/gallery/53.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-54',
    src: '/media/gallery/54.jpg',
    image: '/media/gallery/54.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-55',
    src: '/media/gallery/55.jpg',
    image: '/media/gallery/55.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-56',
    src: '/media/gallery/56.jpg',
    image: '/media/gallery/56.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-57',
    src: '/media/gallery/57.jpg',
    image: '/media/gallery/57.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-58',
    src: '/media/gallery/58.jpg',
    image: '/media/gallery/58.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-59',
    src: '/media/gallery/59.jpg',
    image: '/media/gallery/59.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-60',
    src: '/media/gallery/60.jpg',
    image: '/media/gallery/60.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-61',
    src: '/media/gallery/61.jpg',
    image: '/media/gallery/61.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-62',
    src: '/media/gallery/62.jpg',
    image: '/media/gallery/62.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-63',
    src: '/media/gallery/63.jpg',
    image: '/media/gallery/63.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-64',
    src: '/media/gallery/64.jpg',
    image: '/media/gallery/64.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
  {
    id: 'gallery-65',
    src: '/media/gallery/65.jpg',
    image: '/media/gallery/65.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    objectPosition: 'object-center',
    featured: false,
  },
];

/**
 * Small curated homepage preview selection (4 unique official photographs)
 * Carefully selected from items unique to Gallery to avoid duplicating
 * collection photographs shown in Discover the Collections.
 */
export const HOMEPAGE_GALLERY_PREVIEW_ITEMS: GalleryItem[] = [
  {
    id: 'gallery-01',
    src: '/media/gallery/1.jpg',
    image: '/media/gallery/1.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    featured: false,
  },
  {
    id: 'gallery-05',
    src: '/media/gallery/5.jpg',
    image: '/media/gallery/5.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    featured: false,
  },
  {
    id: 'gallery-09',
    src: '/media/gallery/9.jpg',
    image: '/media/gallery/9.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    featured: false,
  },
  {
    id: 'gallery-11',
    src: '/media/gallery/11.jpg',
    image: '/media/gallery/11.jpg',
    category: 'all-moments',
    categoryLabel: 'Bridal Stories',
    title: 'BEAJAY Bridal Moment',
    alt: 'BEAJAY bridal gallery photograph',
    caption: 'Bridal moments, fittings, details and stories from BEAJAY.',
    aspectRatio: 'aspect-[3/4]',
    orientation: 'portrait',
    featured: false,
  },
];

/**
 * Full editorial registry exported as GalleryItem array for consumption across the app
 */
export const EDITORIAL_GALLERY_REGISTRY: GalleryItem[] = OFFICIAL_GALLERY_ITEMS.map((item) => ({
  id: item.id,
  title: item.title,
  alt: item.alt,
  category: item.category,
  categoryLabel: item.categoryLabel,
  image: item.image,
  src: item.src,
  caption: item.caption,
  orientation: item.orientation,
  aspectRatio: item.aspectRatio,
  objectPosition: item.objectPosition,
  featured: item.featured,
}));
